Implement plotting of non-time based data
ToolDAQ/WebServer pull request #12
Opened 2024-03-14 18:33 UTC by jini-zh

2024-07-16 17:51 UTC, jini-zh commented
This pull request should be merged together with ToolDAQ/ToolDAQFramework#23, ToolDAQ/middleman#6, ToolDAQ/libDAQInterface#9

2024-08-01 14:13 UTC, brichards64 commented on cgi-bin/Makefile
> +	$(CXX) -o $@ $< $(CXXFLAGS) -lzmq -lcgicc -lStore
need chmod

2024-08-01 14:13 UTC, brichards64 commented on cgi-bin/Makefile
> +	$(CXX) -o $@ $< $(CXXFLAGS) -lzmq -lcgicc -lStore
need chmod

2024-08-01 14:14 UTC, brichards64 commented on Dockerfile.server
> +    echo "export LD_LIBRARY_PATH=/lib/:/opt/ToolFrameworkCore/lib:/opt/ToolDAQFramework/lib:/opt/boost_1_66_0/install/lib:/opt/zeromq-4.0.7/lib:/opt/libpqxx-6.4.5/install/lib:$LD_LIBRARY_PATH" >> /et
why is this needed

2024-08-01 14:16 UTC, brichards64 commented on cgi-bin/getplot.cpp
> +#include <pqxx/connection>
we need to discuss this and see if it should be going direct.

2024-08-01 14:17 UTC, brichards64 requested changes
some changes, need to discuss the direct thingwith marcus

2024-08-02 11:20 UTC, jini-zh commented
Should I add `GetPlot` to `html-Detector/include/functions.js`? If yes, we need a way to avoid duplicating JS code otherwise it will inevitably diverge.

2024-08-13 12:40 UTC, merged